catalog:
  '@astrojs/db': ^0.14.8
  '@astrojs/check': ^0.9.4
  '@astrojs/node': ^9.1.2
  '@studiocms/blog': 0.1.0-beta.13
  '@studiocms/devapps': 0.1.0-beta.13
  '@types/node': ^22.0.0
  astro: ^5.5
  astro-integration-kit: ^0.18
  sharp: ^0.33.5
  studiocms: 0.1.0-beta.13
  typescript: ^5.7
  vite: ^6.2.5

catalogs:
  min:
    astro: ^5.5
    studiocms: 0.1.0-beta.13
    '@astrojs/db': ^0.14.7
    vite: ^6.2.0

packages:
  - "packages/*"
  - "playground"
  - "build-scripts"
